### ISSUE TITLE
make script recognize changes to devices, groups, chains and tracks

### ISSUE THREAD

**Issue by markusschloesser** [markusschloesser/MackieC4_P3#16]
in order to be able to recognize changes to devices (unfold etc) and tracks (groups, folding), let's change the script to either: 

1. use the LOM instead of building a local DB(replace local "DB" with LOM)
2. use a local DB but update it from the LOM (currently not really happening)
Question 1: What would be the better approach?

Question 2: If we choose Option 1, a lot needs to be changed before we kick out the local DB, otherwise nothings working. So do we accept that and start by changing to LOM and THEN rework the calls that fail, or first rework the calls to use the LOM and THEN kick out the DB?

**Comment by markusschloesser** [comment]
@BilldarBagdar maybe a stupid question for you, but in order to replace the local index with LOM why can't I just change:
`self.t_current = 0  # index of current selected track`  to `self.t_current = Live.Song.Song.View.selected_track`
and
`self.t_d_count = [0 for i in range(SETUP_DB_DEFAULT_SIZE)]` to `self.t_d_count = Live.Track.Track.devices` 
and
`self.t_d_current = [0 for i in range(SETUP_DB_DEFAULT_SIZE)]` to `self.t_d_current = Live.Track.Track.View.selected_device`
etc?
Might be my naive thinking, but this seems a rather easy approach?

**Comment by markusschloesser** [comment]
to answer myself :D this leads to this:

```
2021-03-15T15:51:32.448218: info: RemoteScriptError:   File "C:\ProgramData\Ableton\Live 11 Beta\Resources\MIDI Remote Scripts\MackieC4_EXP\MackieC4.py", line 322, in track_change
2021-03-15T15:51:32.448509: info: RemoteScriptError: self.__encoder_controller.track_added(selected_index - 1)
2021-03-15T15:51:32.448581: info: RemoteScriptError:   File "C:\ProgramData\Ableton\Live 11 Beta\Resources\MIDI Remote Scripts\MackieC4_EXP\EncoderController.py", line 233, in track_added
2021-03-15T15:51:32.448816: info: RemoteScriptError: for d in range(self.t_d_count[t]):
2021-03-15T15:51:32.448883: info: RemoteScriptError: TypeError
2021-03-15T15:51:32.448947: info: RemoteScriptError: 'property' object is not subscriptable

```
and

```
2021-03-15T15:51:36.164347: info: RemoteScriptError:   File "C:\ProgramData\Ableton\Live 11 Beta\Resources\MIDI Remote Scripts\MackieC4_EXP\MackieC4.py", line 322, in track_change
2021-03-15T15:51:36.164638: info: RemoteScriptError: self.__encoder_controller.track_added(selected_index - 1)
2021-03-15T15:51:36.164706: info: RemoteScriptError:   File "C:\ProgramData\Ableton\Live 11 Beta\Resources\MIDI Remote Scripts\MackieC4_EXP\EncoderController.py", line 250, in track_added
2021-03-15T15:51:36.164934: info: RemoteScriptError: self.t_d_count[track_index] = len(devices_on_selected_track)
2021-03-15T15:51:36.164998: info: RemoteScriptError: TypeError
2021-03-15T15:51:36.165061: info: RemoteScriptError: 'property' object does not support item assignment

```
and an especially bad (in ondisplaytime, so 100s of those)

```
2021-03-15T15:51:48.397617: info: RemoteScriptError:   File "C:\ProgramData\Ableton\Live 11 Beta\Resources\MIDI Remote Scripts\MackieC4_EXP\MackieC4.py", line 146, in update_display
2021-03-15T15:51:48.397886: info: RemoteScriptError: c.on_update_display_timer()
2021-03-15T15:51:48.397958: info: RemoteScriptError:   File "C:\ProgramData\Ableton\Live 11 Beta\Resources\MIDI Remote Scripts\MackieC4_EXP\EncoderController.py", line 1001, in on_update_display_timer
2021-03-15T15:51:48.398520: info: RemoteScriptError: upper_string1 += str(self.t_d_current[self.t_current])
2021-03-15T15:51:48.398598: info: RemoteScriptError: TypeError
2021-03-15T15:51:48.398674: info: RemoteScriptError: 'property' object is not subscriptable

```
So quite obviously it's not that easy and would need more replacing and deleting of functions

**Comment by BilldarBagdar** [comment]
> `self.t_current = 0 # index of current selected track` to `self.t_current = Live.Song.Song.View.selected_track`
> and
> `self.t_d_count = [0 for i in range(SETUP_DB_DEFAULT_SIZE)]` to `self.t_d_count = Live.Track.Track.devices`
> and
> `self.t_d_current = [0 for i in range(SETUP_DB_DEFAULT_SIZE)]` to `self.t_d_current = Live.Track.Track.View.selected_device`
> etc?

This is an assignment of the numeric integer value 0 to the class variable t_current 
`self.t_current = 0`
This is an assignment of the LOM object named selected_track to the class variable t_current 
`self.t_current = Live.Song.Song.View.selected_track`

As the script is written, t_current is a "pointer variable" (it's also a list index pointer), that "points to" the "track list" track index of the "currently selected track" in that track list.  So the "big list db" has the Lists, and also, the pointers to locations in the lists. Similarly, t_d_count and t_d_current are "lists of index variables".  (The range list construction just initializes all of the 128 default list indexes to the value 0.  Then theoretically, when you "change selected tracks" the updated number of devices on the new t_current track would update the t_d_count at the t_current index with the new number of devices value.

In a certain sense though, don't let those errors scare you.  Be bold.  I think you have the right idea.  But you just don't have the experience under your belt to tell you it's ok to keep going.  Even if you forge ahead into an inextricable mess all you have to do is abandon the branch and start a new branch.  

Now, with that said,  you also need to be patient and examine the errors and surrounding code carefully.  For example, why would the change you made cause the failure that occurred?
`self.t_d_count[track_index] = len(devices_on_selected_track)` 
devices_on_selected_track appears to be a list one can take the length of, so this assignment appears to be assigning an integer value (the number of devices on the selected track, the length of the list) to the t_d_count list at the "track_index" index location.

Can you see how this `'property' object does not support item assignment` error might occur after initialization of the t_d_count class member variable was changed to `self.t_d_count = Live.Track.Track.devices`?  t_d_count is no longer a length 128 list of integer values, it is likely a list of however many Live.Track.Track.devices "device objects" (a list that could still be "indexed by an integer value" but `self.t_current` is no longer an integer value. t_current was also updated to the non-integer "selected_track" object value)

Chin up!  Try, test, repair, and try again is the circle of programming.  :)

You might find you can just replace all of the t_xxx, t_d_xxx, and t_d_p_xxx lists in one fell swoop.  I suspect the "count" lists contain values that represent the true "list sizes" at runtime, and the "current" lists contain values that represent the "selected item in the list" at runtime.  So for example, if you had track 1 of 4 selected, and device 1 of 4 selected, then t_count would equal 4 (meaning 4 of the 128 list indexes are "good" because 4 tracks are loaded in the Live session) and t_current would equal 1 (or 0 for list index because the first Track is selected in the Live session).  Similarly, t_d_count would be 4 and t_d_current would be 1 (or 0 as a list index) because that's what's happened in Live, and so on with the parameters of the selected device on the selected track.  If you can just logically rebuild that whole "database" based on LOM objects and concepts so it makes more sense to you, then go for it.  There's nothing sacred to the original code.

**Comment by markusschloesser** [comment]
I need to gain more experience, you are correct. So for now, I am working on the stable branch and look at this (exp) branch later.
Also this makes my head hurt 😂 
I will read it an 11th time tomorrow.
Thanks for the valuable and extensive explanation!!

**Comment by markusschloesser** [comment]
observations:
1. `dvcNme` (meaning somethings wrong, cos there is no device) is only shown on group tracks
2. when adding a device onto that group and then undoing we get vomit

```
RemoteScriptError:   File "C:\ProgramData\Ableton\Live 11 Beta\Resources\MIDI Remote Scripts\MackieC4\MackieC4.py", line 183, in update_display
RemoteScriptError: c.on_update_display_timer()
RemoteScriptError:   File "C:\ProgramData\Ableton\Live 11 Beta\Resources\MIDI Remote Scripts\MackieC4\EncoderController.py", line 1211, in on_update_display_timer
RemoteScriptError: lower_string2 += self.__generate_6_char_string(str(l_alt_text))
RemoteScriptError: Boost.Python
RemoteScriptError: ArgumentError
RemoteScriptError: Python argument types in
    DeviceParameter.__str__(DeviceParameter)
did not match C++ signature:
    __str__(class TPyHandle<class ATimeableValue>)
Python: INFO:MackieC4.MackieC4:864 - (MackieC4) Not enough devices loaded and __chosen_device is not None: name display blank over device index 0
```
probably because `dvcNme` is not a timeable value but a `str`

**Comment by markusschloesser** [comment]
example:
1. parameter amount changes of devices are not recognized
