### ISSUE TITLE
script doesn't disconnect / "destroy"

### ISSUE THREAD

**Issue by markusschloesser** [markusschloesser/MackieC4_P3#19]
When quitting Live, the C4 is not properly disconnected (destroyed in remote script speak). Means Encoders are still lighted, the displays show the last thing they had on etc.

**Comment by BilldarBagdar** [comment]
Are you sure that is supposed to happen?  I only ask because I guess I thought that was supposed to happen.  I mean when I am using the C4 together with the "Commander app" and I quit out of "Commander", IIRC, the C4 display continues showing whatever was the last "screen display" from Commander.

I suspect if you want to wipe the display, all you would need to do is "prepare the data" for a "blank display" (or goodbye message), and then call on_display_update() "one last time" (from inside _destroy() maybe?)  [I suspect one could also just ignore "all the data" and hard code a blank or goodbye message to display in the same way that "user mode" does nothing but display a message.]

**Comment by markusschloesser** [comment]
Yep, the normal Mackie scripts do that (reset faders, reset displays) and there's lots of code about destroy and disconnect, which is obviously not functioning

**Comment by markusschloesser** [comment]
Additionally there are quite a few index errors thrown when closing Live, I suspect it's caused by the "not happening destroy" (comments in code for where it's happening)

**Comment by markusschloesser** [comment]
half fixed in latest branch (vpots are now unlightened), next step: clear displays

**Comment by markusschloesser** [comment]
fixed in https://github.com/markusschloesser/MackieC4_P3/commit/b81083a74fb8684a702833a8f52f38ba34e7e9ca
