### ISSUE TITLE
stop errors from filling the log file

### ISSUE THREAD

**Issue by markusschloesser** [markusschloesser/MackieC4_P3#20]
We need some form of stop for the bad filling the log file rapidly. I mean it's helpful to know shit is happening but we don't need it to potentially crash Live or fill the log file up soooo massively (which results in Live deleting it at some point, which is a) good, cos it doesn't grow too big and b) bad because we loose a history of errors).
How about a "bad shit is happening here, you gotta fix this" error message when this is happening?

**Comment by BilldarBagdar** [comment]
The main issue I think is just a problem "developers like us" need to deal with.  The idea is that hopefully the "log filling issue" does not get released "to the public", and also if it's persistent (and we can't / couldn't fix the issue) we should probably put a **warning** in the README.  

The reason the log fills up like that (and it happened a lot last Spring when I was working on this) is because, for example, methods with names that start with "on" like on_display_update() are "callback methods" associated with "listeners" .  The C4 script "registers itself" with Live and says in effect, "when Live gets to the "display update" part of the "execution cycle"  (the runtime running "loop"), call my on_display_update() method so I can update my display with changes in the app".  (We say the C4 scripts "listens for" when Live's "display update" event fires.  But the actual mechanism is Live "calls (back)" the registered on_display_update() method)  That running loop is very tight, "on display update" only gets called once per second, IIRC, which is only like once every 10 times around the execution loop or whatever.  The end result though is that if there is an error inside on_display_update(), that error will be hit and logged once every second, every time the method is called.

All we can do as developers is watch out for it.  If we are making changes to methods that could cause "runaway logging" like on_display_update(), then we need to remember to check logs right away the first time Live runs those changes.

This is definitely a situation where having a "real debugger" would be a lifesaver.  With a real debugger "attached" to your running code, you can set "breakpoints" and stop the "execution loop" right before the "bug" and examine the "state" of the system that is about to go haywire.  Quite often, a quick glance at the "state" reveals exactly why the next line is going to make the app vomit in the log.  Unfortunately, we don't have that luxury.  We have to get our clues by cleaning up the messes we create.

Also, on_display_update() is in a sense **the** critical method in the script because it handles providing visual feedback to users via the device display.

**Comment by BilldarBagdar** [comment]
...and this is also how we do "log debugging".  We look for the "last correct thing" that was logged and then try to figure out how the code went "off the rails" before what should have been the next correct thing logged.  In this sense leaving yourself "breadcrumb" log messages is a bit like setting actual breakpoints.  You only get to analyze the information you logged instead of the entire "frozen system", but it's something over nothing.

**Comment by markusschloesser** [comment]
> The main issue I think is just a problem "developers like us" need to deal with. The idea is that hopefully the "log filling issue" does not get released "to the public", and also if it's persistent (and we can't / couldn't fix the issue) we should probably put a **warning** in the README.

MS:
1. we could alternatively just "disconnect", imho the better approach (also makes finding errors in the log file easier). The script now sometimes does that. There's also a "with component guard" thing in a lot of the other scripts, which I need to look into 
2. The warning has been there since the beginning :-)



> The reason the log fills up like that (and it happened a lot last Spring when I was working on this) is because, for example, methods with names that start with "on" like on_display_update() are "callback methods" associated with "listeners" . The C4 script "registers itself" with Live and says in effect, "when Live gets to the "display update" part of the "execution cycle" (the runtime running "loop"), call my on_display_update() method so I can update my display with changes in the app". (We say the C4 scripts "listens for" when Live's "display update" event fires. But the actual mechanism is Live "calls (back)" the registered on_display_update() method) That running loop is very tight, "on display update" only gets called once per second, IIRC, which is only like once every 10 times around the execution loop or whatever. The end result though is that if there is an error inside on_display_update(), that error will be hit and logged once every second, every time the method is called.

It's more often, it's every 100ms, so 10 times per second

> 
> All we can do as developers is watch out for it. If we are making changes to methods that could cause "runaway logging" like on_display_update(), then we need to remember to check logs right away the first time Live runs those changes.
> 
> This is definitely a situation where having a "real debugger" would be a lifesaver. With a real debugger "attached" to your running code, you can set "breakpoints" and stop the "execution loop" right before the "bug" and examine the "state" of the system that is about to go haywire. Quite often, a quick glance at the "state" reveals exactly why the next line is going to make the app vomit in the log. Unfortunately, we don't have that luxury. We have to get our clues by cleaning up the messes we create.
> 
> Also, on_display_update() is in a sense **the** critical method in the script because it handles providing visual feedback to users via the device display.

MS have you had a look at the pylive debugging thread? https://forum.ableton.com/viewtopic.php?f=4&t=240667&p=1782092

**Comment by BilldarBagdar** [comment]
That's a very interesting post. It's relatively new, just last fall.  Looks like it's a 2.7 solution for Live 10.  Does the technique still work in 11?

My only concern would be about "enabling telnet" initially.  But I'm also thinking something exactly like that is what the people on the thread over at PyCharm are looking for.  If they jump all over using the technique, then it would help calm my nerves.  I've done "remote debugging" of Java processes, but for example, I was able to connect to the remote Java process I was debugging right from my associated project in Eclipse.  The difference is, I think, I was in control of the command line to start the remote Java process (so I could tell it to listen for "remote debug connections" on whatever port), and Live is in control of the command line that starts the equivalent remote Python process.  This technique seems to indicate remote-pdb doesn't need permission or whatever from the "host Python" process Live starts and it can still "stop the Python bytecode in its tracks" and let you "step through" the Python code with somewhat rudimentary looking set of commands. (although I'm sure the actual feature set is richer)  I wonder how much useful information is available from "a traceback around the current line of code".

I think you are correctly hinting at...  One of these `Debugger().set_trace()` breakpoints inside on_display_update() would stop the log vomit and let you step up to the threshold and look around.  I also suspect doing that could crash Live.  Like you said, that method is called a LOT.  If it's called from a timing loop every 100 ms, then it is expected to have completed and returned within 100 ms.  I'm not saying having breakpoints won't be a game changer. But I am saying there will probably be problems this solution won't be able to assist with.

**Comment by markusschloesser** [comment]
I haven't tried that, also hesitant about telnet ;-)

**Comment by BilldarBagdar** [comment]
One thing you could do is just stop updating the display after the first error.

The basic premise would be to set a Boolean variable at the very top of the method `currently_updating_display = True`, for example, and unset that value at the bottom, to "guard the middle"  It would look something like this:
```
(first line in method)
if currently_updating_display == True:
    return # don't update display while still updating (after exception thrown)
else:
    currently_updating_display = True

# do all method business

(last line in method) 
currently_updating_display = False
```

You won't get log vomit - but you might get frustrated when the display "randomly" stops updating...

**Comment by BilldarBagdar** [comment]
Note: currently_updating_display would have to be a class level variable, not a method local variable for this to work
