### ISSUE TITLE
Parameter values are not shown

### ISSUE THREAD

**Issue by markusschloesser** [markusschloesser/MackieC4_P3#3]
Parameter values are not shown (which I know is possible because it works on the Mackie Control Pro, again see Photos)
The second line on the C4 should show parameter values. It does not and I currently don't know where the code for that is.

Update: (Copy from readme cos better place here)
Parameter values are not shown in **Plugin Mode** (which I know is possible because it works on the Mackie Control Pro, again see the 2 Photos in Google Photos for comparison https://photos.app.goo.gl/m3NXgJcQeLvtHaZZA~~), also the encoders light ring shows "values", so it's gotta be somewhere. And it works in track mode! 

What I don't understand is, everywhere in the Ableton scripts parameters and values are clearly derived from the LOM, so the "Live.DeviceParameter.DeviceParameter.value" should give me what I want. And in all original LIVE scripts exactly that is called/accessed, BUT NOT in the Mackie scripts. There everywhere where there should be that, instead vpot_parameter is used and I can't find ANY reference to DeviceParameter

**Comment by BilldarBagdar** [comment]
If you look at lines around (currently) 496, 97, 98 in EncoderControllers.py  you will find a comment where I think at least one issue root is.  In "channel mode" the "handle vpot rotation" method only handles "twisting events" for 2 encoders. You can "Mute" or  "Record Arm" the selected Track by twisting clockwise or anti-clockwise controllers 29 and 30. (twist one way to mute, the other way to un-mute for example)  That same comment points to Encoders.build_mid_map() where the "parameter values" you want to see might be mapped.  The C4 -> Live mapping goes in the Live.MidiMap.map_midi_cc_with_feedback_map() method, and the Live -> C4 direction goes in the other method call a few lines down after the comment lines Live.MidiMap.send_feedback_for_parameter().  

That Encoders "feedback mapping" may not even really work in the script though.  For example, I suspect the "Volume" and "Pan" encoders actually display feedback in channel strip mode because of lines (currently) between 806 and 830 in the EncoderController.reassign_controller_parameters() method.  Controllers 31 and 32 are handled in their own "else if blocks" and, for example, I think the vpot_display_text = (self.selected_track.mixer_device.volume, 'Volume') tuple assignment makes the "volume parameter" value visible with feedback on the C4.  With that said, the stuff specific to controllers 31 and 32 in EncoderController.reassign_controller_parameters() method could just be a hack to get volume and pan feedback even though the full feedback mapping was broken.  I guess only Leigh would know.  Hope he stops by sometime.

**Comment by markusschloesser** [comment]
will look into this! However the whole build_mid_map() thing is still something I do not understand properly. I have a feeling that once the boost error is fixed, lots of other things might magically will work as well 😇
btw would it be ok for you if I posted what you wrote by mail last week? (Or of course if you could do that)

**Comment by BilldarBagdar** [comment]
I'm not sure what part of what I wrote last week you want to post so I think you should post what you want of what I wrote and maybe I can comment further from there or whatever.  Just don't mention those very embarrassing things I said about powerful public figures :)
  
  
   
  
  
   I don't really understand the whole "build midi map" thing either.  But I suspect that is key to bi-directional messaging (feedback value display).  The thing is, I don't really understand why the script goes to all the effort of keeping track of all the devices and parameters loaded on all (visible?) tracks in its own (database) collection of lists when that information is always available from Live "live" in real time anyway. (which is I think why the vol and pan visual feedback works.  The script is getting the info directly from the LOM, I think, in those last lines I mentioned) I don't know, maybe it's just more efficient to collect it all once when a track or device is added or removed than collecting specific information every time that information is needed.  I mean, when for example, the selected device changes in device view, the script needs to remap all of the encoders to all of the parameters of the new device.  But instead of querying Live (the LOM) for that info right when it is needed, IIRC, this script already has that info stored (or is supposed to have it stored correctly) locally for "faster updates" I guess.  It seems very easy to me for there to be a lot of room for errors, too much room, because it's so easy to get "off by one" when you are addressing everything by 2, 3, 4 dimension addresses in 2, 3, 4 dimension lists instead of just asking the source for the data as needed.
  
  
   
    On 03/06/2021 7:01 PM markusschloesser <notifications@github.com> wrote:
   
   
    
   
   
    
   
   
   will look into this! However the whole build_mid_map() thing is still something I do not understand properly. I have a feeling that once the boost error is fixed, lots of other things might magically will work as well 😇btw would it be ok for you if I posted what you wrote by mail last week? (Or of course if you could do that)

**Comment by BilldarBagdar** [comment]
> What I don't understand is, everywhere in the Ableton scripts parameters and values are clearly derived from the LOM, so the "Live.DeviceParameter.DeviceParameter.value" should give me what I want. And in all original LIVE scripts exactly that is called/accessed, BUT NOT in the Mackie scripts. There everywhere where there should be that, instead vpot_parameter is used and I can't find ANY reference to DeviceParameter

Yes - that is what I've been talking about, everything in this script uses (for lack of a better word) indirection.  Instead of directly calling something out of the LOM like Live.DeviceParameter.DeviceParameter.value and doing something with that value, this script maintains its own "database" of all device parameters of all devices on all tracks, and so here instead you see calls into the "list database" instead of calls to the LOM.

If I understand correctly, I think maybe you should study the __reorder_parameters(self) method in EncoderController, as well as the __reassign_encoder_parameters(self) method.  I believe those two methods are responsible for "populating" the tuples that are referred to as vpot_parameter in other places.

Specifically, a line like this `result = [(p, p.name) for p in self.__chosen_plugin.parameters]`  where `(p, p.name)` is the tuple that gets referred to by the name vpot_parameter, and "result" is a list of tuples representing all "Device Parameter" objects and their names. ('p' is the object and 'p.name' is the name; so when the tuple is accessed as vpot_parameter, you see a lot of references to vpot_param[0] - the object and vpot_param[1] - the name)  IIRC - this is code I had to "clean up" because IIRC, vpot_parameter wasn't always populated the same way.  Like sometimes the first item, the zero index, the "object" wouldn't be set if only the "name part" was needed or something.  That's why I added this logging
`self.main_script().log_message("Param {0} name <{1}>".format(count, p[1]))`

**Comment by markusschloesser** [comment]
fixed in latest MS_stable 😊😊😊, this `vpot_display_text = (plugin_param[0], plugin_param[1])` was the solution. It is fucking awesome to have the values there
![image](https://user-images.githubusercontent.com/59286549/111854985-8482f380-8922-11eb-9544-5a694e17851b.png)
It even updates somewhat, so for example if a device does not auto-populate it's parameters and you then go and do the "configure" thing in Live and add all parameters, you need to reselect the device and params are shown.
Oh and I switched it around, so param name on top, param value below.
