### ISSUE TITLE
redundancies in code

### ISSUE THREAD

**Issue by markusschloesser** [markusschloesser/MackieC4_P3#45]
https://github.com/markusschloesser/MackieC4_P3/blob/2e3bfb09cfbfd7903053bf1b4388551831492ea4/wip/MackieC4/EncoderController.py#L895
https://github.com/markusschloesser/MackieC4_P3/blob/2e3bfb09cfbfd7903053bf1b4388551831492ea4/wip/MackieC4/EncoderController.py#L1114
both are about displaying arming, but only the second one is used

**Comment by BilldarBagdar** [comment]
:)  Yes - hence the comment.  Why did Leigh do that?  I assume because there was some bug (possibly long dead by now) that was preventing the first way from working correctly and he chose not to find and fix the root, but to add more code to paper over the problem, to make it less visible.

The first way is the "reassign encoder parameters" way, the designed way - but remember how problematic it has been to keep "on display update" from "uncontrollably" vomiting in the log?  The second way is the "I give up looking for the true source. I'm just going to hack in a change I know will work and get moving again" way.  (Also known as the "I found the true source, but it's too much (time, effort, complexity, whatever) to fix properly. I'm just going to hack in a change..." way)  I've gone both ways on that kind of search myself. I mean I've given up and hacked in a quick fix from both perspectives.  In a sense you are still making the same  (time, effort, complexity, whatever) calculation and decision, just at an earlier stage in the investigation.  

It will be easy enough to refactor "on display update" to, for example, like: 
```
#lower_string4 += '  ON   '  
lower_string4 += text_for_display.get_text()   
```
in all those "hard coded" places in "on display update" .

But look at the "LOM status looking" conditions controlling the hard coded display values.  I would bet the "design way" might not be working (still) because, for example, the Mute On/Off status display value (that would be the return from `get_text()`) isn't updated correctly or at all in the script "as designed" when the On/Off status changes.  But here in "on display update", by checking Live's Track Mute Status directly, for example, and hard coding what to display; one can bypass such a "design challenge" and move on.  This (wager worthy) theory would be easy enough to test, right.  Either going to the "new" EncoderDisplaySegment `get_text()` way will work correctly right away after the change or it won't.  If it doesn't, then we have the same (time, effort, complexity, whatever) calculation and decision to make.  Paper right back over the crack?  :)

**Comment by markusschloesser** [comment]
it's even worse, there are actually more places where "stuff to display" is implemented. In addition to the two from above (`__reassign_encoder_parameters`, `on_update_display_timer` ) there's also `__reorder_parameters` , `__send_parameter` , `__plugin_parameter`

**Comment by markusschloesser** [comment]
it's not redundancy, things actually need to be implemented at multiple places right now, see https://github.com/markusschloesser/MackieC4_P3/discussions/73#discussioncomment-4014856
