### ISSUE TITLE
scroll in arrange view with vpot and show Song position in display for Beats or SMPTE, also vpot ring 

### ISSUE THREAD

**Issue by markusschloesser** [markusschloesser/MackieC4_P3#93]
use 
`self.song.jump_by(factor)` 
or
`                if backwards:
                    self.song().jump_by(-step)
                else:
                    self.song().jump_by(step)`
for the actual jog dial feature (step or factor: try with "1" and "-1))

**Comment by markusschloesser** [comment]
use TimeDisplay.py as inspiration for SPP display

**Comment by markusschloesser** [comment]
https://github.com/markusschloesser/MackieC4_P3/commit/9fc3aa4b0fb7c19e8579772940fc390c77fffa5e implements 1 and 2.
Now the only thing missing is showing the progress of the song on the vpot ring

**Comment by markusschloesser** [comment]
> If you are still having trouble finding those full "song length" detail data, what about making the rings "mark time" to indicate the progress of the song? One ring advances one "click" every beat, the next advances every 4 beats, the next every 16 beats, whatever. The hard parts there I guess would be making that "encoder ring count" reset with the "song transport" and keeping it going whenever the song is going so the count display remains "accurate" if you go away and then come back to that time display mode. You could maybe even get fancy for example making that first "every beat" ring use "spread" mode so it alternates between fully spread (lit) and fully off every other beat (maybe it goes from open to closed over the 4 sixteenth notes in every beat, then back).

Thanks!
As I am starting slowly to run out of vpots and wanna start easy, I'll stick to one vpot for the moment (vpot12 which is also the "jog dial" vpot for bars, maybe add vpot 13 for beats later, but that might get distracting with too much action going on).
Keeping it accurate shouldn't be a problem when I do the updating in on_update_display_timer ((don't know if you saw the commit notes? I moved a couple of display in Function mode things to on_update_display_timer, which guarantees that it's always accurate)
I do have the full length `(Live.Song.Song.song_length),` but as written in the other ticket, have trouble calculating what I need.

**Comment by BilldarBagdar** [comment]
Lol, I'm still catching up on all the various "new things", and I have a lot of practice at procrastination under my belt.

Is that song_length value an accumulated value that "grows" with each beat and measure every time the Song starts, or does it statically mark the end of the "last clip" in Arrangement mode (if one exists)?

For example, I generally only work "live" in Session mode and almost never record any clips in Arrangement mode (recording is done on another machine where the digital audio output from 3 instances of Live can be mixed).  If I do record something in Arrangement mode, it's usually because I want to create a new clip and bring the clip back to Session mode (then I delete any clips in Arrangement mode because I'm done with them).  

Does "song_length" store any meaningful values in that situation?

**Comment by markusschloesser** [comment]
> Is that song_length value an accumulated value that "grows" with each beat and measure every time the Song starts, or does it statically mark the end of the "last clip" in Arrangement mode (if one exists)?

It grows, you can see that when using loop length and too quickly expand, then the log complains about "can't go further than song end", if you wait a sec, than song end "expands"

visual metronome shouldn't be a problem

**Comment by markusschloesser** [comment]
implemented with https://github.com/markusschloesser/MackieC4_P3/commit/ee7e49628f2d46b0b0ca22632abb0a81e2bb0377
